SET IDENTITY_INSERT ADDPRODUCT ON;

IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 22)
    INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (22, 'Cold Pressed Mustard Oil', 349, 100, 'Oil & Ghee');

IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 23)
    INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (23, 'Desi Cow Ghee', 1099, 100, 'Oil & Ghee');

IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 27)
    INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (27, 'Organic Toor Dal', 185, 100, 'Pulses & Dal');

IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 45)
    INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (45, 'Organic Makhana', 499, 100, 'Dry Fruits & Nuts');

SET IDENTITY_INSERT ADDPRODUCT OFF;
GO
