SET IDENTITY_INSERT ADDPRODUCT ON;

-- 1. Combos & Deals
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 1) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (1, 'Breakfast Combo Pack', 1099, 100, 'Combos & Deals');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 2) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (2, 'Masalas Combo', 950, 100, 'Combos & Deals');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 3) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (3, 'Dry Fruits Combo', 1299, 100, 'Combos & Deals');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 4) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (4, 'Healthy Family Combo', 1499, 100, 'Combos & Deals');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 5) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (5, 'Cold Pressed Oils Combo', 899, 100, 'Combos & Deals');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 6) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (6, 'Everyday Spices Combo', 1199, 100, 'Combos & Deals');

-- 2. Flours & Suji
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 7) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (7, 'Organic Wheat Flour', 199, 100, 'Flours & Suji');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 8) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (8, 'Organic Suji', 159, 100, 'Flours & Suji');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 9) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (9, 'Organic Besan', 189, 100, 'Flours & Suji');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 10) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (10, 'Multigrain Flour', 249, 100, 'Flours & Suji');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 11) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (11, 'Organic Ragi Flour', 179, 100, 'Flours & Suji');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 12) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (12, 'Organic Rice Flour', 169, 100, 'Flours & Suji');

-- 3. Rice & Rice Products
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 13) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (13, 'Sona Masuri Rice', 239, 100, 'Rice & Rice Products');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 14) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (14, 'Red Rice', 299, 100, 'Rice & Rice Products');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 15) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (15, 'Ponni Rice', 219, 100, 'Rice & Rice Products');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 16) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (16, 'Basmati Rice', 349, 100, 'Rice & Rice Products');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 17) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (17, 'Black Rice', 399, 100, 'Rice & Rice Products');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 18) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (18, 'Idli Rice', 189, 100, 'Rice & Rice Products');

-- 4. Oil & Ghee
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 19) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (19, 'Cold-Pressed Groundnut Oil', 349, 100, 'Oil & Ghee');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 20) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (20, 'Cold-Pressed Sesame Oil', 499, 100, 'Oil & Ghee');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 21) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (21, 'Cold-Pressed Coconut Oil', 299, 100, 'Oil & Ghee');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 22) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (22, 'Cold-Pressed Mustard Oil', 259, 100, 'Oil & Ghee');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 23) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (23, 'Desi Cow Ghee', 1299, 100, 'Oil & Ghee');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 24) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (24, 'A2 Desi Cow Ghee', 1499, 100, 'Oil & Ghee');

-- 5. Pulses & Dal
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 25) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (25, 'Organic Moong Dal', 149, 100, 'Pulses & Dal');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 26) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (26, 'Organic Kala Chana', 120, 100, 'Pulses & Dal');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 27) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (27, 'Organic Toor Dal', 185, 100, 'Pulses & Dal');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 28) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (28, 'Organic Chana Dal', 130, 100, 'Pulses & Dal');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 29) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (29, 'Organic Moong Dal Whole', 160, 100, 'Pulses & Dal');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 30) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (30, 'Organic Urad Dal White', 180, 100, 'Pulses & Dal');

-- 6. Salts, Sugar & Jaggery
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 31) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (31, 'Organic Rock Salt', 99, 100, 'Salts, Sugar & Jaggery');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 32) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (32, 'Organic Sugar', 120, 100, 'Salts, Sugar & Jaggery');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 33) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (33, 'Organic Wild Forest Honey', 450, 100, 'Salts, Sugar & Jaggery');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 34) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (34, 'Jaggery Powder', 180, 100, 'Salts, Sugar & Jaggery');

-- 7. Teas & Coffee
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 35) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (35, 'Tulsi Lemon Tea', 300, 100, 'Teas & Coffee');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 50) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (50, 'Filter Coffee', 249, 100, 'Teas & Coffee');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 51) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (51, 'Green Tea', 269, 100, 'Teas & Coffee');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 52) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (52, 'Tulsi Ginger Tea', 229, 100, 'Teas & Coffee');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 53) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (53, 'Black Tea', 189, 100, 'Teas & Coffee');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 54) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (54, 'Tulsi Masala Tea', 299, 100, 'Teas & Coffee');

-- 8. Spices & Masalas
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 36) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (36, 'Organic Turmeric Powder', 120, 100, 'Spices & Masalas');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 37) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (37, 'Organic Red Chilli Powder', 140, 100, 'Spices & Masalas');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 38) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (38, 'Organic Coriander Powder', 130, 100, 'Spices & Masalas');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 39) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (39, 'Organic Garam Masala', 150, 100, 'Spices & Masalas');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 40) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (40, 'Organic Cumin Whole', 110, 100, 'Spices & Masalas');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 41) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (41, 'Black Pepper Whole', 160, 100, 'Spices & Masalas');

-- 9. Dry Fruits & Nuts
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 42) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (42, 'Organic Walnuts', 300, 100, 'Dry Fruits & Nuts');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 43) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (43, 'Organic Almonds', 280, 100, 'Dry Fruits & Nuts');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 44) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (44, 'Organic Cashews', 220, 100, 'Dry Fruits & Nuts');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 45) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (45, 'Organic Makhana', 579, 100, 'Dry Fruits & Nuts');

-- 10. Health Foods
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 46) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (46, 'Chia Seeds', 119, 100, 'Health Foods');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 47) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (47, 'Flax Seeds', 78, 100, 'Health Foods');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 48) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (48, 'Psyllium Husk', 149, 100, 'Health Foods');
IF NOT EXISTS (SELECT 1 FROM ADDPRODUCT WHERE ID = 49) INSERT INTO ADDPRODUCT (ID, NAME, PRICE, STOCK, CATEGORY) VALUES (49, 'Quinoa', 199, 100, 'Health Foods');

SET IDENTITY_INSERT ADDPRODUCT OFF;
GO
