const fs = require('fs');
const path = require('path');

const products = [
  {
    id: 1,
    name: "Breakfast Combo Pack",
    price: "₹1099",
    category: "Combos & Deals",
    img: "/img1.png",
  },
  {
    id: 2, 
    name: "Masalas Combo",
    price: "₹950",
    category: "Combos & Deals",
    img: "/img2.png",
  },
  {
    id: 3,
    name: "Dry Fruits Combo",
    price: "₹1,299",
    category: "Combos & Deals",
    img: "/img3.png",
  },
  {
    id: 4,
    name: "Healthy Family Combo",
    price: "₹1,499",
    category: "Combos & Deals",
    img: "/img4.png",
  },
  {
    id: 5,
    name: "Cold Pressed Oils Combo",
    price: "₹899",
    category: "Combos & Deals",
    img: "/img5.png",
  },
  {
    id: 6,
    name: "Everyday Spices Combo",
    price: "₹1,199",
    category: "Combos & Deals",
    img: "/img6.png",
  },
  { id: 7, 
    name: "Organic Wheat Flour",
    price: "₹199",
    category: "Flours & Suji",
    img: "/img7.png",
  },
  { id: 8, 
    name: "Organic Suji",
    price: "₹159",
    category: "Flours & Suji",
    img: "/img8.png" ,
  },
  { id: 9,
    name: "Organic Besan", 
    price: "₹189",
    category: "Flours & Suji",
    img: "/img9.png" ,
  },
  { id: 10,
    name: "Multigrain Flour", 
    price: "₹249",
    category: "Flours & Suji",
    img: "/img10.png" ,
  },
  { id: 11,
    name: "Organic Ragi Flour",
    price: "₹179",
    category: "Flours & Suji",
    img: "/img11.png" ,
  },
  { id: 12,
    name: "Organic Rice Flour", 
    price: "₹169", 
    category: "Flours & Suji",
    img: "/img12.png",
  },
  { id: 13,
    name: "Sona Masuri Rice",
    price: "₹239",
    category: "Rice & Rice Products", 
    img: "/img13.png",
  },
  { id: 14, 
    name: "Red Rice", 
    price: "₹299", 
    category: "Rice & Rice Products", 
    img: "/img14.png" ,
  },
  { id: 15, 
    name: "Ponni Rice", 
    price: "₹219", 
    category: "Rice & Rice Products", 
    img: "/img15.png" ,
  },
  { id: 16, 
    name: "Basmati Rice", 
    price: "₹349", 
    category: "Rice & Rice Products", 
    img: "/img16.png",
  },
  { id: 17, 
    name: "Black Rice", 
    price: "₹399", 
    category: "Rice & Rice Products", 
    img: "/img17.png" ,
  },
  { id: 18, 
    name: "Idli Rice", 
    price: "₹189", 
    category: "Rice & Rice Products", 
    img: "/img18.png" ,
  },
  { id: 19, 
    name: "Cold-Pressed Groundnut Oil", 
    price: "₹349", 
    category: "Oil & Ghee", 
    img: "/img19.png" ,
  },
  { id: 20, 
    name: "Cold-Pressed Sesame Oil", 
    price: "₹499", 
    category: "Oil & Ghee", 
    img: "/img20.png" ,
  },
  { id: 21, 
    name: "Cold-Pressed Coconut Oil", 
    price: "₹299", 
    category: "Oil & Ghee", 
    img: "/img21.png" ,
  },
  { id: 22, 
    name: "Cold-Pressed Mustard Oil", 
    price: "₹259", 
    category: "Oil & Ghee", 
    img: "/img22.png",
  },
  { id: 23, 
    name: "Almond Oil", 
    price: "₹899", 
    category: "Oil & Ghee", 
    img: "/img23.png",
  },
  { id: 24, 
    name: "Virgin Olive Oil", 
    price: "₹699", 
    category: "Oil & Ghee", 
    img: "/img24.png" ,
  },
  { id: 25, 
    name: "Cow Ghee", 
    price: "₹699", 
    category: "Oil & Ghee", 
    img: "/img25.png" ,
  },
  { id: 26, 
    name: "A2 Desi Cow Ghee", 
    price: "₹1,299", 
    category: "Oil & Ghee", 
    img: "/img26.png" ,
  },
  { id: 27, 
    name: "Buffalo Ghee", 
    price: "₹749", 
    category: "Oil & Ghee", 
    img: "/img27.png" ,
  },
  { id: 28, 
    name: "Turmeric Powder", 
    price: "₹120", 
    category: "Spices & Masalas", 
    img: "/img28.png",
  },
  { id: 29, 
    name: "Organic Honey", 
    price: "₹450", 
    category: "Salts, Sugar & Jaggery", 
    img: "/img29.png" ,
  },
  { id: 30, 
    name: "Jaggery Powder", 
    price: "₹180", 
    category: "Salts, Sugar & Jaggery", 
    img: "/img30.png" ,
  },
  { id: 31, 
    name: "Palm Jaggery", 
    price: "₹250", 
    category: "Salts, Sugar & Jaggery", 
    img: "/img31.png" ,
  },
  { id: 32, 
    name: "Stevia Powder", 
    price: "₹300", 
    category: "Salts, Sugar & Jaggery", 
    img: "/img32.png" ,
  },
  { id: 33, 
    name: "Brown Sugar", 
    price: "₹120", 
    category: "Salts, Sugar & Jaggery", 
    img: "/img33.png" ,
  },
  { id: 34, 
    name: "Date Syrup", 
    price: "₹280", 
    category: "Salts, Sugar & Jaggery", 
    img: "/img34.png" ,
  },
  { id: 35, 
    name: "Turmeric Powder", 
    price: "₹120", 
    category: "Spices & Masalas", 
    img: "/img35.png" ,
  },
   { id: 38, 
    name: "Red Chilli Powder", 
    price: "₹140", 
    category: "Spices & Masalas", 
    img: "/img37.png" ,
  },
  { id: 39, 
    name: "Coriander Powder", 
    price: "₹130", 
    category: "Spices & Masalas", 
    img: "/img38.png" ,
  },
  { id: 40, 
    name: "Garam Masala", 
    price: "₹150", 
    category: "Spices & Masalas", 
    img: "/img39.png" ,
  },
  { id: 41, 
    name: "Cumin Whole", 
    price: "₹110", 
    category: "Spices & Masalas", 
    img: "/img40.png" ,
  },
  { id: 42, 
    name: "Black Pepper Whole", 
    price: "₹160", 
    category: "Spices & Masalas", 
    img: "/img41.png" ,
  },
  { id: 43, 
    name: "Walnuts", 
    price: "₹300", 
    category: "Dry Fruits & Nuts", 
    img: "/img42.png" ,
  },
  { id: 44, 
    name: "Almonds", 
    price: "₹280", 
    category: "Dry Fruits & Nuts", 
    img: "/img43.png" ,
  },
  { id: 45, 
    name: "Cashews", 
    price: "₹220", 
    category: "Dry Fruits & Nuts", 
    img: "/img44.png" ,
  },
  { id: 48, 
    name: "Makhana", 
    price: "₹579", 
    category: "Dry Fruits & Nuts", 
    img: "/img45.png" ,
  },
  { id: 49, 
    name: "Chia Seeds", 
    price: "₹119", 
    category: "Health Foods", 
    img: "/img46.png" ,
  },
  { id: 50, 
    name: "Flax Seeds", 
    price: "₹78", 
    category: "Health Foods", 
    img: "/img47.png" ,
  },
  { id: 51, 
    name: "Psyllium Husk", 
    price: "₹149", 
    category: "Health Foods", 
    img: "/img48.png" ,
  },
  { id: 52, 
    name: "Quinoa", 
    price: "₹199", 
    category: "Health Foods", 
    img: "/img49.png" ,
  },
  { id: 53, 
    name: "Foxtail Millet", 
    price: "₹169", 
    category: "Health Foods", 
    img: "/img50.png" ,
  },
  { id: 54, 
    name: "Ragi Whole", 
    price: "₹139", 
    category: "Health Foods", 
    img: "/img51.png" ,
  },
  { id: 55, 
    name: "Filter Coffee", 
    price: "₹249", 
    category: "Teas & Coffee", 
    img: "/img52.png" ,
  },
  { id: 56, 
    name: "Green Tea", 
    price: "₹269", 
    category: "Teas & Coffee", 
    img: "/img53.png" ,
  },
  { id: 57, 
    name: "Tulsi Lemon Tea", 
    price: "₹399", 
    category: "Teas & Coffee", 
    img: "/img54.png" ,
  },
  { id: 58, 
    name: "Tulsi Ginger Tea", 
    price: "₹229", 
    category: "Teas & Coffee", 
    img: "/img55.png" ,
  },
  { id: 59, 
    name: "Black Tea", 
    price: "₹189", 
    category: "Teas & Coffee", 
    img: "/img56.png" ,
  },
  { id: 60, 
    name: "Tulsi Masala Tea", 
    price: "₹299", 
    category: "Teas & Coffee", 
    img: "/img57.png" ,
  }
];

async function migrate() {
  console.log("Starting migration...");
  const loginRes = await fetch('http://localhost:5249/api/Auth/login', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({Email: "bindu@gmail.com", Password: "bindu@123"})
  });
  const auth = await loginRes.json();
  if(!auth.token) {
    console.error("Failed to login", auth);
    return;
  }

  let success = 0;
  for (const p of products) {
    const formData = new FormData();
    formData.append('Name', p.name);
    
    const numericString = String(p.price).replace(/[^0-9.]/g, '');
    const numericPrice = parseFloat(numericString) || 0;
    formData.append('Price', numericPrice.toString());
    formData.append('Stock', '100'); // generic default
    formData.append('Category', p.category);

    const imgName = p.img.startsWith('/') ? p.img.substring(1) : p.img;
    const imgPath = path.join('d:/FinalYearProject/OrganicProducts/public', imgName);
    
    if (fs.existsSync(imgPath)) {
      const buffer = fs.readFileSync(imgPath);
      const blob = new Blob([buffer], { type: 'image/png' });
      formData.append('imageFile', blob, imgName);
    } else {
      console.log(`Image not found: ${imgPath}`);
    }

    try {
      const res = await fetch('http://localhost:5249/api/Products', {
        method: 'POST',
        headers: { 'Authorization': 'Bearer ' + auth.token },
        body: formData
      });
      const txt = await res.text();
      if(res.ok) {
        success++;
      } else {
        console.log(`Failed to add ${p.name}: ${res.status} ${txt}`);
      }
    } catch(e) {
      console.error(`Exception on ${p.name}:`, e);
    }
  }
  console.log(`Migration complete. Successfully added ${success}/${products.length} products.`);
}

migrate();
